webapp/main/routes.py
from flask import Blueprint
from flask.templating import render_template
from flask_login import login_required


main = Blueprint("main", __name__, template_folder="templates")


@main.route("/account")
@login_required
def account():
    return render_template("account.html")

webapp/main/templates/account.html
{% extends "layout.html" %}
{% set active_page = "account" %}
{% block content %}

{% endblock content %}

webapp/main/templates/layout.html
<!DOCTYPE html>
<html>

<head>
    <!-- Required meta tags for bootstrap-->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <!-- Favicon -->
    <link rel="shortcut icon" href="{{ url_for('static', filename='pictures/favicon.ico') }}">

    <!-- Our CSS -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    <!-- Font Awesome CSS -->
    <link rel='stylesheet' href="{{ url_for('static', filename='fontawesome5/css/all.min.css')}}">

    <!-- JQuery -->
    <script type="text/javascript" src="https://code.jquery.com/jquery-1.11.3.min.js"></script>

    <!-- Datepicker -->
    <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css"
        integrity="sha256-siyOpF/pBWUPgIcQi17TLBkjvNgNQArcmwJB8YvkAgg=" crossorigin="anonymous" />

    <!-- MDBootstrap Datatables  -->
    <link href="{{ url_for('static', filename='mdb-4/css/addons/datatables2.min.css')}}" rel="stylesheet">
    <link href="https://cdn.datatables.net/buttons/1.6.1/css/buttons.dataTables.min.css" rel="stylesheet">

    <!-- set title depending on the current site -->
    {% if active_page == 'dashboard' %}
    <title>UTime - Dashboard</title>
    {% elif active_page == 'employee_list' %}
    <title>UTime - Mitarbeiter</title>
    {% elif active_page == 'overview' %}
    <title>UTime - Übersicht</title>
    {% elif active_page == 'account' %}
    <title>UTime - Mein Konto</title>
    {% elif active_page == 'login' %}
    <title>UTime - Login</title>
    {% else %}
    <title>UTime</title>
    {% endif %}
</head>

<body class="bg-mercury">
    <div class="container-fluid h-100-70px">
        <div class="row h-70px border-bottom border-secondary fixed-top m-0">
            <div class="col-2 bg-dark">
                <!-- uTime Logo with link to the dashboard -->
                <a class="nav-link text-center align-middle" href="{{ url_for('timestamp_dashboard.dashboard') }}">
                    <!-- /Static, weil sonst bei tieferer Navigation asdf/asdf/... uTime.svg nicht gefunden wird -->
                    <img src="{{ url_for('static', filename='pictures/UTime.svg')}}" alt="UTime" height="50">
                </a>
            </div>
            <div class="col-6 bg-mercury">
                <h2 class="d-inline-flex align-items-center h-100 ml-5">
                    <!-- set header depending on the current site -->
                    {% if active_page == 'dashboard' %}
                    Dashboard
                    {% elif active_page == 'employee_list' %}
                    Mitarbeiter
                    {% elif active_page == 'overview' %}
                    Übersicht
                    {% elif active_page == 'account' %}
                    Mein Konto
                    {% elif active_page == 'login' %}
                    Login
                    {% else %}

                    {% endif %}
                </h2>
            </div>
            {% if active_page != 'login' %}
            <div class="col-2 bg-mercury">
                <!-- decoration for better optic -->
                <a class="d-inline-flex align-items-center text-secondary h-100 text-decoration-none">
                    <i class="fas fa-bell fa-2x mr-3 fa-fw"></i>Benachrichtigungen</a>
            </div>
            <!-- show the currently logged in user and his role -->
            <div class="col-2 bg-mercury">
                <div class="d-inline-flex align-items-center text-secondary h-100">
                    <i class="fas fa-user-circle fa-2x mr-3 fa-fw"></i>
                    {{ current_user.first_name }} {{ current_user.last_name }} <br>
                    {% if current_user.role == '1' %}
                    Personalsachbearbeiter
                    {% elif current_user.role == '0' %}
                    Mitarbeiter
                    {% endif %}
                </div>
            </div>
            {% endif %}
        </div>
        <div class="row mt-70px">
            <!-- if current site is not the login, show all navbar items -->
            {% if active_page != 'login' %}
            <div class="col-2 bg-dark position-fixed h-100">
                <a class="nav-link mt-5 {{ 'text-info' if active_page == 'dashboard' else 'text-light' }}"
                    href="{{ url_for('timestamp_dashboard.dashboard') }}">
                    <i class="fas fa-home fa-2x mr-5 fa-fw"></i>Dashboard</a>
                <!-- "Mitarbeiter" is shown only to personal administrators -->
                {% if current_user.role == '1' %}
                <a class="nav-link mt-2 {{ 'text-info' if active_page == 'employee_list' else 'text-light' }}"
                    href="{{ url_for('employee_administration.employee_list') }}">
                    <i class="fas fa-user fa-2x mr-5 fa-fw"></i>Mitarbeiter</a>
                {% endif %}
                <a class="nav-link mt-2 {{ 'text-info' if active_page == 'overview' else 'text-light' }}"
                    href="{{ url_for('timestamp_overview.overview') }}">
                    <i class="fas fa-chart-bar fa-2x mr-5 fa-fw"></i>Übersicht</a>
                <a class="nav-link mt-2 {{ 'text-info' if active_page == 'account' else 'text-light' }}"
                    href="{{ url_for('main.account') }}">
                    <i class="fas fa-clock fa-2x mr-5 fa-fw"></i>Mein Konto</a>
                <a class="col-2 nav-link mb-5 ml-3 text-danger fixed-bottom"
                    href="{{ url_for('authentication.logout') }}">
                    <i class="fas fa-sign-out-alt fa-2x mr-5 fa-fw"></i>Abmelden</a>
            </div>
            <!-- else only show login item -->
            {% else %}
            <div class="col-2 bg-dark position-fixed h-100">
                <a class="nav-link mt-5 text-info" href="{{ url_for('authentication.login') }}">
                    <i class="fa fa-sign-in-alt fa-2x mr-5 fa-fw"></i>Login</a>
            </div>
            {% endif %}
            <div class="col-10 mt-3 position-absolute right-0">
                <!-- section for the flash messages -->
                <div>
                    {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                    {% for category, message in messages %}
                    <div class="alert alert-{{ category }} mt-3">
                        {{ message }}
                        <i class="fa fa-times fa-lg cursor-pointer float-right" onclick=delete_flash(this)></i>
                    </div>

                    <script>
                        // close the flash message on the X-Item
                        function delete_flash(flash) {
                            $(flash).parent().remove()
                        }
                    </script>
                    {% endfor %}
                    {% endif %}
                    {% endwith %}

                    {% block content %}{% endblock %}
                </div>
            </div>
        </div>
    </div>

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
    <!-- Bootstrap DataTable -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"
        integrity="sha256-bqVeqGdJ7h/lYPq6xrPv/YGzMEb6dNxlfiTUHSgRCp8=" crossorigin="anonymous"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='mdb-4/js/addons/datatables2.min.js')}}"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.6.1/js/dataTables.buttons.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.6.1/js/buttons.flash.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.6.1/js/buttons.html5.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.6.1/js/buttons.print.min.js"></script>

</body>

</html>

webapp/main/templates/overview.html
{% extends "layout.html" %}
{% set active_page = "overview" %}
{% block content %}

{% endblock content %}